/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Institute;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class AddCourses extends javax.swing.JFrame {

    /**
     * Creates new form AddCourses
     */
    public AddCourses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        cname = new javax.swing.JTextField();
        elg = new javax.swing.JTextField();
        fee = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dur = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        updt = new javax.swing.JButton();
        add = new javax.swing.JButton();
        dlt = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add courses");
        setBackground(new java.awt.Color(204, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Course_id:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(56, 74, 107, 37);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Course_name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(56, 129, 144, 37);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Eligibility:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(56, 193, 144, 37);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Fee:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(56, 259, 121, 37);

        cid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null));
        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });
        getContentPane().add(cid);
        cid.setBounds(253, 85, 242, 22);

        cname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null));
        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });
        getContentPane().add(cname);
        cname.setBounds(253, 140, 242, 22);

        elg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null));
        elg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elgActionPerformed(evt);
            }
        });
        getContentPane().add(elg);
        elg.setBounds(253, 204, 242, 22);

        fee.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null));
        fee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeActionPerformed(evt);
            }
        });
        fee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                feeKeyTyped(evt);
            }
        });
        getContentPane().add(fee);
        fee.setBounds(253, 270, 242, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Duration:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(56, 322, 121, 37);

        dur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null));
        dur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durActionPerformed(evt);
            }
        });
        getContentPane().add(dur);
        dur.setBounds(253, 322, 242, 22);

        reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset);
        reset.setBounds(652, 339, 240, 31);

        updt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updt.setText("Update");
        updt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updtActionPerformed(evt);
            }
        });
        getContentPane().add(updt);
        updt.setBounds(633, 146, 140, 44);

        add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add);
        add.setBounds(652, 276, 240, 31);

        dlt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dlt.setText("Delete");
        dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltActionPerformed(evt);
            }
        });
        getContentPane().add(dlt);
        dlt.setBounds(783, 146, 109, 44);

        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(652, 208, 240, 31);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Show Courses");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(634, 80, 260, 57);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 926, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 20, 930, 450);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 590);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 153), 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(592, 50, 320, 361);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void elgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elgActionPerformed

    private void feeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feeActionPerformed

    private void durActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        
        cid.setText("");
        cname.setText("");
        elg.setText("");
        fee.setText("");
        dur.setText("");
        
    }//GEN-LAST:event_resetActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        
         int ans = JOptionPane.showConfirmDialog(null, "Are you sure want to add course");
        if(ans == JOptionPane.YES_OPTION)
        {

            try{
                Class.forName("java.sql.Driver");

      Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Institute","root","123");

       
      PreparedStatement pst = con.prepareStatement("insert into courses values(?,?,?,?,?)");
               
               pst.setString(2,cname.getText());
           pst.setString(1,cid.getText());
                pst.setString(3,elg.getText());
                pst.setInt(4,Integer.parseInt(fee.getText()));
                pst.setString(5,dur.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "course add succesfully");
            }
            catch (Exception e){
             JOptionPane.showMessageDialog(null, e);
            }}
        if(ans == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null, "course not added");
        }
         if(ans == JOptionPane.CANCEL_OPTION){
             JOptionPane.showMessageDialog(null, "Operation cancel ");
         }
        
        
    }//GEN-LAST:event_addActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Courses c1 = new Courses();
        c1.setVisible(true);

       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        
        Functioncourses fc =new Functioncourses();
        
        ResultSet rs= null;
        String cd ="course_id";
        String cn ="course_name";
        String eg ="eligibility";
        String fe ="fee";
        String du="duration";
        
        rs =fc.find(cid.getText());
        try{
            if(rs.next()){
                cid.setText(rs.getString("course_id"));
                
                cname.setText(rs.getString("course_name"));
                elg.setText(rs.getString("eligibility"));
                fee.setText(rs.getString("fee"));
                dur.setText(rs.getString("duration"));
                
            }else{
                JOptionPane.showMessageDialog(null, "No Data For this ID");
            }
        
        
    }
        catch(Exception e)
        {
            
        }
    }
        public class Functioncourses
        {
       
            Connection con =null;
        ResultSet rs=null;
        PreparedStatement ps =null;
        public ResultSet find(String s){
        try{
            con =DriverManager.getConnection("jdbc:mysql://localhost/Institute","root","123");
       ps =con.prepareStatement("select* from courses where course_id=?");
       ps.setString(1, s);
       rs =ps.executeQuery();
       
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
         return rs;
        }
      
    }//GEN-LAST:event_searchActionPerformed

    private void dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltActionPerformed
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure want to delete course");
        if(ans == JOptionPane.YES_OPTION)
        {

            try{
                Class.forName("java.sql.Driver");

      Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Institute","root","123");
             PreparedStatement pst = con.prepareStatement("delete from courses where course_id= ?");
             pst.setString(1, (cid.getText()));
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "Record deleted successfully");
             
        cid.setText("");
        cname.setText("");
        elg.setText("");
        fee.setText("");
        dur.setText("");
        
            }
            
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
            
       
            }
        if(ans== JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null, "Record not deleted");
            
        }
         if(ans == JOptionPane.CANCEL_OPTION){
             JOptionPane.showMessageDialog(null, "Operation cancel ");
         }
        
        
        
    }//GEN-LAST:event_dltActionPerformed

    private void updtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updtActionPerformed
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure want to update course record");
        if(ans == JOptionPane.YES_OPTION)
        {

            try{
                Class.forName("java.sql.Driver");

      Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Institute","root","123");
      PreparedStatement pst = con.prepareStatement("update courses set course_name=?, eligibility=?, fee=?, duration =? where course_id=? ");
               
        pst.setString(1, cname.getText());
        pst.setString(2, elg.getText());
         pst.setString(3, fee.getText());
        pst.setString(4, dur.getText());
        pst.setString(5, cid.getText());
       
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Record updated successfully");
            }
        
        catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
        }
        } 
        if(ans == JOptionPane.NO_OPTION){
            JOptionPane.showMessageDialog(null, "Record not updated ");
        }
         if(ans == JOptionPane.CANCEL_OPTION){
             JOptionPane.showMessageDialog(null, "Operation cancel ");
         }
        
    }//GEN-LAST:event_updtActionPerformed

    private void feeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_feeKeyTyped
        // TODO add your handling code here:
        
        if(!Character.isDigit(evt.getKeyChar())){
          evt.consume();    
            }
    }//GEN-LAST:event_feeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCourses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AddCourses().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cname;
    private javax.swing.JButton dlt;
    private javax.swing.JTextField dur;
    private javax.swing.JTextField elg;
    private javax.swing.JTextField fee;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton reset;
    private javax.swing.JButton search;
    private javax.swing.JButton updt;
    // End of variables declaration//GEN-END:variables
}
