/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Institute;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hp
 */
public class Teacher extends javax.swing.JFrame {

    /**
     * Creates new form Teacher
     */
    public Teacher() {
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        loc = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        qual = new javax.swing.JTextField();
        exp = new javax.swing.JTextField();
        sal = new javax.swing.JTextField();
        pas = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teachers");
        setMaximumSize(new java.awt.Dimension(1180, 770));
        setMinimumSize(new java.awt.Dimension(1180, 770));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Teacher_name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 105, 143, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Contact no. :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 208, 116, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Location:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 159, 84, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Qualification:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 259, 122, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Password:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 425, 94, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Experienced:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 319, 119, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Salary:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 369, 63, 22);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(29, 29, 29))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(23, 506, 380, 130);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Institute/teacher1.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(540, 197, 300, 195);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Institute/Faculty1.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(896, 207, 180, 149);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1180, 770));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Teacher_Id:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(12, 18, 176, 22);

        tid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tid.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidActionPerformed(evt);
            }
        });
        jPanel2.add(tid);
        tid.setBounds(250, 20, 153, 28);

        tname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });
        jPanel2.add(tname);
        tname.setBounds(250, 110, 150, 28);

        loc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        loc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locActionPerformed(evt);
            }
        });
        jPanel2.add(loc);
        loc.setBounds(250, 160, 160, 28);

        contact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        contact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactActionPerformed(evt);
            }
        });
        jPanel2.add(contact);
        contact.setBounds(250, 210, 160, 28);

        qual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        qual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualActionPerformed(evt);
            }
        });
        jPanel2.add(qual);
        qual.setBounds(250, 260, 160, 28);

        exp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expActionPerformed(evt);
            }
        });
        jPanel2.add(exp);
        exp.setBounds(250, 320, 160, 28);

        sal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salActionPerformed(evt);
            }
        });
        jPanel2.add(sal);
        sal.setBounds(246, 365, 170, 28);

        pas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(0, 0, 0), null, null));
        pas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasActionPerformed(evt);
            }
        });
        jPanel2.add(pas);
        pas.setBounds(246, 420, 170, 28);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("D.O.B");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(12, 61, 176, 22);

        dob.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(dob);
        dob.setBounds(250, 60, 160, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("Show Records");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(580, 40, 202, 37);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1180, 770);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidActionPerformed

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locActionPerformed

    private void contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactActionPerformed

    private void qualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qualActionPerformed

    private void salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salActionPerformed

    private void expActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expActionPerformed

    private void pasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tid.setText("");
        tname.setText("");
        loc.setText("");
        contact.setText("");
        dob.setCalendar(null);
        qual.setText("");
        exp.setText("");
        sal.setText("");
        pas.setText("");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         int ans = JOptionPane.showConfirmDialog(null, "Are you sure want to add teacher");
        if(ans == JOptionPane.YES_OPTION)
        {

            try{
                Class.forName("java.sql.Driver");

      Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Institute","root","123");

       
      PreparedStatement pst = con.prepareStatement("insert into teachers values(?,?,?,?,?,?,?,?,?)");
               
               pst.setString(1, (tid.getText()));
               pst.setString(2,tname.getText());
               
               SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
               String date=sdf.format(dob.getDate());
               pst.setString(3, date);
          
                pst.setString(4,loc.getText());
                pst.setInt(5,Integer.parseInt(contact.getText()));
                pst.setString(6,qual.getText());
                 pst.setString(7,exp.getText());
                
                 pst.setInt(8, Integer.parseInt(sal.getText()));
                  pst.setString(9,pas.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Teacher  add succesfully");
               
            }
            catch (Exception e){
             JOptionPane.showMessageDialog(null, e);
            }}
        if(ans == JOptionPane.NO_OPTION)
        {
            JOptionPane.showMessageDialog(null, "Teacher not added");
            
        }
          if(ans == JOptionPane.CANCEL_OPTION){
             JOptionPane.showMessageDialog(null, "Operation cancel ");
         }                  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
       Teachertable t =new Teachertable();
       t.setVisible(true);
     
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Function f =new Function();
        
        ResultSet rs= null;
        String tn ="teacher_name";
        String d="dob";
        String lo ="location";
        String co ="contact";
        String qua ="qualification";
        String ex ="experienced";
        String sa ="salary";
        String pa ="password";
        rs =f.find(tid.getText());
        try{
            if(rs.next()){
                
              
                tname.setText(rs.getString("teacher_name"));
                
              //  d= dob.getDate().toString();
                //dob.setDate("dob");
                dob.setDate(rs.getDate("dob"));
                
                loc.setText(rs.getString("location"));
                contact.setText(rs.getString("contact"));
                qual.setText(rs.getString("qualification"));
                exp.setText(rs.getString("experienced"));
                sal.setText(rs.getString("salary"));
                pas.setText(rs.getString("password"));
            }else{
                JOptionPane.showMessageDialog(null, "No Data For this ID");
            }
        
        
    }
        catch(Exception e)
        {
            
        }
    }
        public class Function
        {
       
            Connection con =null;
        ResultSet rs=null;
        PreparedStatement ps =null;
        public ResultSet find(String s){
        try{
            con =DriverManager.getConnection("jdbc:mysql://localhost/Institute","root","123");
       ps =con.prepareStatement("select* from teachers where teacher_id=?");
       ps.setString(1, s);
       rs =ps.executeQuery();
       
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
         return rs;
        }
      
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
      int ans = JOptionPane.showConfirmDialog(null, "Are you sure want to delete teacher");
        if(ans == JOptionPane.YES_OPTION)
        {

            try{
                Class.forName("java.sql.Driver");

      Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Institute","root","123");
             PreparedStatement pst = con.prepareStatement("delete from teachers where teacher_id= ?");
             pst.setString(1, (tid.getText()));
             pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "Record deleted successfully");
             
        tid.setText("");
        tname.setText("");
        loc.setText("");
        dob.setCalendar(null);
        contact.setText("");
        qual.setText("");
        exp.setText("");
        sal.setText("");
        pas.setText("");
            }
            
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
            }
        if(ans == JOptionPane.NO_OPTION){
             JOptionPane.showMessageDialog(null, "Record not deleted ");
        }
          if(ans == JOptionPane.CANCEL_OPTION){
             JOptionPane.showMessageDialog(null, "Operation cancel ");
         }                  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure want to update teacher record");
        if(ans == JOptionPane.YES_OPTION)
        {

            try{
                Class.forName("java.sql.Driver");

      Connection con = DriverManager.getConnection("jdbc:mysql://localhost/Institute","root","123");
      PreparedStatement pst = con.prepareStatement("update teachers set teacher_name=?,dob=?, location=?, contact=?, qualification=?, experienced =?, salary =?, password=? where teacher_id=? ");
         
        pst.setString(1, tname.getText());
        SimpleDateFormat sdf =new SimpleDateFormat("yyyy-MM-dd");
               String date=sdf.format(dob.getDate());
               pst.setString(2, date);
        pst.setString(3, loc.getText());
        pst.setString(4, contact.getText());
        pst.setString(5, qual.getText());
        pst.setString(6, exp.getText());
        pst.setString(7, sal.getText());
        pst.setString(8, pas.getText());
        pst.setString(9, tid.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Record updated successfully");
        con.close();
            }
            
        
        catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
        }
        }
           if(ans == JOptionPane.NO_OPTION){
               JOptionPane.showMessageDialog(null, "Record not updated ");
               }
          if(ans == JOptionPane.CANCEL_OPTION){
             JOptionPane.showMessageDialog(null, "Operation cancel ");
         }                  
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Teacher().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contact;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField exp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField loc;
    private javax.swing.JTextField pas;
    private javax.swing.JTextField qual;
    private javax.swing.JTextField sal;
    private javax.swing.JTextField tid;
    private javax.swing.JTextField tname;
    // End of variables declaration//GEN-END:variables
}
